version: '3.4'

services:
  microservicetask.apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "50002:80"
  microservicetask.messengermicroservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "50003:80"
  microservicetask.ui:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "50001:80"